import type Cion from '../src/index.ts'

const maintest_isboolean_0: Cion.RawLisp<`(boolean? 1)`> = ['prim', false]
const maintest_isboolean_1: Cion.RawLisp<`(boolean? -1)`> = ['prim', false]
const maintest_isboolean_2: Cion.RawLisp<`(boolean? 29438)`> = ['prim', false]
const maintest_isboolean_3: Cion.RawLisp<`(boolean? '')`> = ['prim', false]
const maintest_isboolean_4: Cion.RawLisp<`(boolean? '102')`> = ['prim', false]
const maintest_isboolean_5: Cion.RawLisp<`(boolean? false)`> = ['prim', true]
const maintest_isboolean_6: Cion.RawLisp<`(boolean? [])`> = ['prim', false]
const maintest_isboolean_7: Cion.RawLisp<`(boolean? [1 2 3])`> = ['prim', false]
const maintest_isboolean_8: Cion.RawLisp<`(boolean? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isboolean_9: Cion.RawLisp<`(boolean? {:x 1 :y 1})`> = ['prim', false]
const maintest_isboolean_10: Cion.RawLisp<`(boolean? nil)`> = ['prim', false]
const maintest_isboolean_11: Cion.RawLisp<`(boolean? (+ 1 2))`> = ['prim', false]
const maintest_isboolean_12: Cion.RawLisp<`(boolean? ((fn [] (+ 1 2))))`> = ['prim', false]
const maintest_isboolean_13: Cion.RawLisp<`(boolean? ((fn [x y] (+ x y)) 1 2))`> = ['prim', false]
const maintest_isboolean_14: Cion.RawLisp<`(boolean? (:x {:x false}))`> = ['prim', true]
const _maintest_isboolean_14: Cion.RawLisp<`(boolean? (:x {:x 1}))`> = ['prim', false]
const maintest_isboolean_15: Cion.RawLisp<`(boolean? (first [true '1' 2]))`> = ['prim', true]
const _maintest_isboolean_15: Cion.RawLisp<`(boolean? (first [0 '1' 2]))`> = ['prim', false]
const maintest_isboolean_16: Cion.RawLisp<`(boolean? (let [x 1 y 2] (+ x y)))`> = ['prim', false]
const maintest_isboolean_17: Cion.RawLisp<`(boolean? (let [] (+ 1 2)))`> = ['prim', false]
const maintest_isboolean_18: Cion.RawLisp<`(boolean? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', false]
