import type Cion from '../src/index.ts'

const maintest_isempty_0: Cion.RawLisp<`(empty? 1)`> = ['prim', false]
const maintest_isempty_1: Cion.RawLisp<`(empty? -1)`> = ['prim', false]
const maintest_isempty_2: Cion.RawLisp<`(empty? 29438)`> = ['prim', false]
const maintest_isempty_3: Cion.RawLisp<`(empty? '')`> = ['prim', false]
const maintest_isempty_4: Cion.RawLisp<`(empty? '102')`> = ['prim', false]
const maintest_isempty_5: Cion.RawLisp<`(empty? true)`> = ['prim', false]
const maintest_isempty_6: Cion.RawLisp<`(empty? [])`> = ['prim', true]
const maintest_isempty_7: Cion.RawLisp<`(empty? [1 2 3])`> = ['prim', false]
const maintest_isempty_8: Cion.RawLisp<`(empty? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isempty_9: Cion.RawLisp<`(empty? {:x 1 :y 1})`> = ['prim', false]
const maintest_isempty_10: Cion.RawLisp<`(empty? nil)`> = ['prim', false]
const maintest_isempty_11: Cion.RawLisp<`(empty? (rest [1]))`> = ['prim', true]
const maintest_isempty_12: Cion.RawLisp<`(empty? ((fn [] [])))`> = ['prim', true]
const maintest_isempty_13: Cion.RawLisp<`(empty? ((fn [x] (rest x)) [1]))`> = ['prim', true]
const maintest_isempty_14: Cion.RawLisp<`(empty? (:x {:x []}))`> = ['prim', true]
const maintest_isempty_15: Cion.RawLisp<`(empty? (first [[] '1' 2]))`> = ['prim', true]
const maintest_isempty_16: Cion.RawLisp<`(empty? (let [x 1 y 2] (rest (rest [x y]))))`> = ['prim', true]
const maintest_isempty_17: Cion.RawLisp<`(empty? (let [] []))`> = ['prim', true]
