import type Cion from '../src/index.ts'

const maintest_iseven_0: Cion.RawLisp<`(even? 1)`> = ['prim', false]
const maintest_iseven_1: Cion.RawLisp<`(even? -1)`> = ['prim', false]
const maintest_iseven_01: Cion.RawLisp<`(even? 2)`> = ['prim', true]
const maintest_iseven_11: Cion.RawLisp<`(even? -2)`> = ['prim', true]
const maintest_iseven_2: Cion.RawLisp<`(even? 29438)`> = ['prim', true]
const maintest_iseven_3: Cion.RawLisp<`(even? '')`> = ['prim', false]
const maintest_iseven_4: Cion.RawLisp<`(even? '102')`> = ['prim', false]
const maintest_iseven_5: Cion.RawLisp<`(even? true)`> = ['prim', false]
const maintest_iseven_6: Cion.RawLisp<`(even? [])`> = ['prim', false]
const maintest_iseven_7: Cion.RawLisp<`(even? [1 2 3])`> = ['prim', false]
const maintest_iseven_8: Cion.RawLisp<`(even? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_iseven_9: Cion.RawLisp<`(even? {:x 1 :y 1})`> = ['prim', false]
const maintest_iseven_10: Cion.RawLisp<`(even? nil)`> = ['prim', false]
const maintest_iseven_110: Cion.RawLisp<`(even? (+ 2 2))`> = ['prim', true]
const maintest_iseven_12: Cion.RawLisp<`(even? ((fn [] (+ 2 2))))`> = ['prim', true]
const maintest_iseven_13: Cion.RawLisp<`(even? ((fn [x y] (+ x y)) 2 2))`> = ['prim', true]
const maintest_iseven_14: Cion.RawLisp<`(even? (:x {:x 2}))`> = ['prim', true]
const maintest_iseven_15: Cion.RawLisp<`(even? (first [0 '1' 2]))`> = ['prim', true]
const maintest_iseven_16: Cion.RawLisp<`(even? (let [x 2 y 2] (+ x y)))`> = ['prim', true]
const maintest_iseven_17: Cion.RawLisp<`(even? (let [] (+ 2 2)))`> = ['prim', true]
const maintest_iseven_18: Cion.RawLisp<`(even? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', true]
