import type Cion from '../src/index.ts'

const maintest_isint_0: Cion.RawLisp<`(int? 1)`> = ['prim', true]
const maintest_isint_00: Cion.RawLisp<`(int? 0)`> = ['prim', true]
const maintest_isint_1: Cion.RawLisp<`(int? -1)`> = ['prim', true]
const maintest_isint_2: Cion.RawLisp<`(int? 29438)`> = ['prim', true]
const maintest_isint_3: Cion.RawLisp<`(int? '')`> = ['prim', false]
const maintest_isint_4: Cion.RawLisp<`(int? '102')`> = ['prim', false]
const maintest_isint_5: Cion.RawLisp<`(int? true)`> = ['prim', false]
const maintest_isint_6: Cion.RawLisp<`(int? [])`> = ['prim', false]
const maintest_isint_7: Cion.RawLisp<`(int? [1 2 3])`> = ['prim', false]
const maintest_isint_8: Cion.RawLisp<`(int? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isint_9: Cion.RawLisp<`(int? {:x 1 :y 1})`> = ['prim', false]
const maintest_isint_10: Cion.RawLisp<`(int? nil)`> = ['prim', false]
const maintest_isint_11: Cion.RawLisp<`(int? (- 1 2))`> = ['prim', true]
const maintest_isint_12: Cion.RawLisp<`(int? ((fn [] (- 1 2))))`> = ['prim', true]
const maintest_isint_13: Cion.RawLisp<`(int? ((fn [x y] (- x y)) 1 2))`> = ['prim', true]
const maintest_isint_14: Cion.RawLisp<`(int? (:x {:x -1}))`> = ['prim', true]
const maintest_isint_15: Cion.RawLisp<`(int? (first [-1 '1' 2]))`> = ['prim', true]
const maintest_isint_16: Cion.RawLisp<`(int? (let [x 1 y 2] (- x y)))`> = ['prim', true]
const maintest_isint_17: Cion.RawLisp<`(int? (let [] (- 1 2)))`> = ['prim', true]
const maintest_isint_18: Cion.RawLisp<`(int? (* 3 (let [x 1 y 2] (- x y))))`> = ['prim', true]

const maintest_isint_diff_0: Cion.RawLisp<`(int? 1/2)`>   = ['prim', false]
const maintest_isint_diff_1: Cion.RawLisp<`(int? -1/2)`>  = ['prim', false]
const maintest_isint_diff_2: Cion.RawLisp<`(int? -3/1)`>  = ['prim', true]
const maintest_isint_diff_3: Cion.RawLisp<`(int? 3/1)`>   = ['prim', true]
const maintest_isint_diff_4: Cion.RawLisp<`(int? -3/-1)`> = ['prim', true]
const maintest_isint_diff_5: Cion.RawLisp<`(int? 3/-1)`>  = ['prim', true]
