import type Cion from '../src/index.ts'

const manatest_isnat_0: Cion.RawLisp<`(nat? 1)`> = ['prim', true]
const manatest_isnat_00: Cion.RawLisp<`(nat? 0)`> = ['prim', true]
const manatest_isnat_1: Cion.RawLisp<`(nat? -1)`> = ['prim', false]
const manatest_isnat_2: Cion.RawLisp<`(nat? 29438)`> = ['prim', true]
const manatest_isnat_3: Cion.RawLisp<`(nat? '')`> = ['prim', false]
const manatest_isnat_4: Cion.RawLisp<`(nat? '102')`> = ['prim', false]
const manatest_isnat_5: Cion.RawLisp<`(nat? true)`> = ['prim', false]
const manatest_isnat_6: Cion.RawLisp<`(nat? [])`> = ['prim', false]
const manatest_isnat_7: Cion.RawLisp<`(nat? [1 2 3])`> = ['prim', false]
const manatest_isnat_8: Cion.RawLisp<`(nat? (fn [x y] (+ x y)))`> = ['prim', false]
const manatest_isnat_9: Cion.RawLisp<`(nat? {:x 1 :y 1})`> = ['prim', false]
const manatest_isnat_10: Cion.RawLisp<`(nat? nil)`> = ['prim', false]
const manatest_isnat_11: Cion.RawLisp<`(nat? (- 1 2))`> = ['prim', false]
const manatest_isnat_12: Cion.RawLisp<`(nat? ((fn [] (- 1 2))))`> = ['prim', false]
const manatest_isnat_13: Cion.RawLisp<`(nat? ((fn [x y] (- x y)) 1 2))`> = ['prim', false]
const manatest_isnat_14: Cion.RawLisp<`(nat? (:x {:x -1}))`> = ['prim', false]
const manatest_isnat_15: Cion.RawLisp<`(nat? (first [-1 '1' 2]))`> = ['prim', false]
const manatest_isnat_16: Cion.RawLisp<`(nat? (let [x 1 y 2] (- x y)))`> = ['prim', false]
const manatest_isnat_17: Cion.RawLisp<`(nat? (let [] (- 1 2)))`> = ['prim', false]
const manatest_isnat_18: Cion.RawLisp<`(nat? (* 3 (let [x 1 y 2] (- x y))))`> = ['prim', false]

const manatest_isnat_diff_0: Cion.RawLisp<`(nat? 1/2)`>   = ['prim', false]
const manatest_isnat_diff_1: Cion.RawLisp<`(nat? -1/2)`>  = ['prim', false]
const manatest_isnat_diff_2: Cion.RawLisp<`(nat? -3/1)`>  = ['prim', false]
const manatest_isnat_diff_3: Cion.RawLisp<`(nat? 3/1)`>   = ['prim', true]
const manatest_isnat_diff_4: Cion.RawLisp<`(nat? -3/-1)`> = ['prim', true]
const manatest_isnat_diff_5: Cion.RawLisp<`(nat? 3/-1)`>  = ['prim', false]
