import type Cion from '../src/index.ts'

const maintest_isneg_0: Cion.RawLisp<`(neg? 1)`> = ['prim', false]
const maintest_isneg_1: Cion.RawLisp<`(neg? -1)`> = ['prim', true]
const maintest_isneg_2: Cion.RawLisp<`(neg? 29438)`> = ['prim', false]
const maintest_isneg_3: Cion.RawLisp<`(neg? '')`> = ['prim', false]
const maintest_isneg_4: Cion.RawLisp<`(neg? '102')`> = ['prim', false]
const maintest_isneg_5: Cion.RawLisp<`(neg? true)`> = ['prim', false]
const maintest_isneg_6: Cion.RawLisp<`(neg? [])`> = ['prim', false]
const maintest_isneg_7: Cion.RawLisp<`(neg? [1 2 3])`> = ['prim', false]
const maintest_isneg_8: Cion.RawLisp<`(neg? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isneg_9: Cion.RawLisp<`(neg? {:x 1 :y 1})`> = ['prim', false]
const maintest_isneg_10: Cion.RawLisp<`(neg? nil)`> = ['prim', false]
const maintest_isneg_11: Cion.RawLisp<`(neg? (- 1 2))`> = ['prim', true]
const maintest_isneg_12: Cion.RawLisp<`(neg? ((fn [] (- 1 2))))`> = ['prim', true]
const maintest_isneg_13: Cion.RawLisp<`(neg? ((fn [x y] (- x y)) 1 2))`> = ['prim', true]
const maintest_isneg_14: Cion.RawLisp<`(neg? (:x {:x -1}))`> = ['prim', true]
const maintest_isneg_15: Cion.RawLisp<`(neg? (first [-1 '1' 2]))`> = ['prim', true]
const maintest_isneg_16: Cion.RawLisp<`(neg? (let [x 1 y 2] (- x y)))`> = ['prim', true]
const maintest_isneg_17: Cion.RawLisp<`(neg? (let [] (- 1 2)))`> = ['prim', true]
const maintest_isneg_18: Cion.RawLisp<`(neg? (* 3 (let [x 1 y 2] (- x y))))`> = ['prim', true]

const maintest_isneg_diff_0: Cion.RawLisp<`(neg? 1/2)`>   = ['prim', false]
const maintest_isneg_diff_1: Cion.RawLisp<`(neg? -1/2)`>  = ['prim', true]
const maintest_isneg_diff_2: Cion.RawLisp<`(neg? -3/1)`>  = ['prim', true]
const maintest_isneg_diff_3: Cion.RawLisp<`(neg? 3/1)`>   = ['prim', false]
const maintest_isneg_diff_4: Cion.RawLisp<`(neg? -3/-1)`> = ['prim', false]
const maintest_isneg_diff_5: Cion.RawLisp<`(neg? 3/-1)`>  = ['prim', true]
