import type Cion from '../src/index.ts'

const maintest_isnegint_0: Cion.RawLisp<`(neg-int? 1)`> = ['prim', false]
const maintest_isnegint_1: Cion.RawLisp<`(neg-int? -1)`> = ['prim', true]
const maintest_isnegint_2: Cion.RawLisp<`(neg-int? 29438)`> = ['prim', false]
const maintest_isnegint_3: Cion.RawLisp<`(neg-int? '')`> = ['prim', false]
const maintest_isnegint_4: Cion.RawLisp<`(neg-int? '102')`> = ['prim', false]
const maintest_isnegint_5: Cion.RawLisp<`(neg-int? true)`> = ['prim', false]
const maintest_isnegint_6: Cion.RawLisp<`(neg-int? [])`> = ['prim', false]
const maintest_isnegint_7: Cion.RawLisp<`(neg-int? [1 2 3])`> = ['prim', false]
const maintest_isnegint_8: Cion.RawLisp<`(neg-int? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isnegint_9: Cion.RawLisp<`(neg-int? {:x 1 :y 1})`> = ['prim', false]
const maintest_isnegint_10: Cion.RawLisp<`(neg-int? nil)`> = ['prim', false]
const maintest_isnegint_11: Cion.RawLisp<`(neg-int? (- 1 2))`> = ['prim', true]
const maintest_isnegint_12: Cion.RawLisp<`(neg-int? ((fn [] (- 1 2))))`> = ['prim', true]
const maintest_isnegint_13: Cion.RawLisp<`(neg-int? ((fn [x y] (- x y)) 1 2))`> = ['prim', true]
const maintest_isnegint_14: Cion.RawLisp<`(neg-int? (:x {:x -1}))`> = ['prim', true]
const maintest_isnegint_15: Cion.RawLisp<`(neg-int? (first [-1 '1' 2]))`> = ['prim', true]
const maintest_isnegint_16: Cion.RawLisp<`(neg-int? (let [x 1 y 2] (- x y)))`> = ['prim', true]
const maintest_isnegint_17: Cion.RawLisp<`(neg-int? (let [] (- 1 2)))`> = ['prim', true]
const maintest_isnegint_18: Cion.RawLisp<`(neg-int? (* 3 (let [x 1 y 2] (- x y))))`> = ['prim', true]

const maintest_isnegint_diff_0: Cion.RawLisp<`(neg-int? 1/2)`>   = ['prim', false]
const maintest_isnegint_diff_1: Cion.RawLisp<`(neg-int? -1/2)`>  = ['prim', false]
const maintest_isnegint_diff_2: Cion.RawLisp<`(neg-int? -3/1)`>  = ['prim', true]
const maintest_isnegint_diff_3: Cion.RawLisp<`(neg-int? 3/1)`>   = ['prim', false]
const maintest_isnegint_diff_4: Cion.RawLisp<`(neg-int? -3/-1)`> = ['prim', false]
const maintest_isnegint_diff_5: Cion.RawLisp<`(neg-int? 3/-1)`>  = ['prim', true]
