import type Cion from '../src/index.ts'
 
const maintest_isnil_0: Cion.RawLisp<`(nil? 1)`> = ['prim', false]
const maintest_isnil_1: Cion.RawLisp<`(nil? -1)`> = ['prim', false]
const maintest_isnil_2: Cion.RawLisp<`(nil? 29438)`> = ['prim', false]
const maintest_isnil_3: Cion.RawLisp<`(nil? '')`> = ['prim', false]
const maintest_isnil_4: Cion.RawLisp<`(nil? '102')`> = ['prim', false]
const maintest_isnil_5: Cion.RawLisp<`(nil? false)`> = ['prim', false]
const maintest_isnil_6: Cion.RawLisp<`(nil? [])`> = ['prim', false]
const maintest_isnil_7: Cion.RawLisp<`(nil? [1 2 3])`> = ['prim', false]
const maintest_isnil_8: Cion.RawLisp<`(nil? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isnil_9: Cion.RawLisp<`(nil? {:x 1 :y 1})`> = ['prim', false]
const maintest_isnil_10: Cion.RawLisp<`(nil? nil)`> = ['prim', true]
const maintest_isnil_11: Cion.RawLisp<`(nil? (+ 1 2))`> = ['prim', false]
const maintest_isnil_12: Cion.RawLisp<`(nil? ((fn [] (+ 1 2))))`> = ['prim', false]
const maintest_isnil_13: Cion.RawLisp<`(nil? ((fn [x y] (+ x y)) 1 2))`> = ['prim', false]
const maintest_isnil_14: Cion.RawLisp<`(nil? (:x {:x 1}))`> = ['prim', false]
const maintest_isnil_15: Cion.RawLisp<`(nil? (first [0 '1' 2]))`> = ['prim', false]
const maintest_isnil_16: Cion.RawLisp<`(nil? (let [x 1 y 2] (+ x y)))`> = ['prim', false]
const maintest_isnil_17: Cion.RawLisp<`(nil? (let [] (+ 1 2)))`> = ['prim', false]
const maintest_isnil_18: Cion.RawLisp<`(nil? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', false]
