import type Cion from '../src/index.ts'
 
const maintest_isnumber_0: Cion.RawLisp<`(number? 1)`> = ['prim', true]
const maintest_isnumber_1: Cion.RawLisp<`(number? -1)`> = ['prim', true]
const maintest_isnumber_2: Cion.RawLisp<`(number? 29438)`> = ['prim', true]
const maintest_isnumber_3: Cion.RawLisp<`(number? '')`> = ['prim', false]
const maintest_isnumber_4: Cion.RawLisp<`(number? '102')`> = ['prim', false]
const maintest_isnumber_5: Cion.RawLisp<`(number? true)`> = ['prim', false]
const maintest_isnumber_6: Cion.RawLisp<`(number? [])`> = ['prim', false]
const maintest_isnumber_7: Cion.RawLisp<`(number? [1 2 3])`> = ['prim', false]
const maintest_isnumber_8: Cion.RawLisp<`(number? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isnumber_9: Cion.RawLisp<`(number? {:x 1 :y 1})`> = ['prim', false]
const maintest_isnumber_10: Cion.RawLisp<`(number? nil)`> = ['prim', false]
const maintest_isnumber_11: Cion.RawLisp<`(number? (+ 1 2))`> = ['prim', true]
const maintest_isnumber_12: Cion.RawLisp<`(number? ((fn [] (+ 1 2))))`> = ['prim', true]
const maintest_isnumber_13: Cion.RawLisp<`(number? ((fn [x y] (+ x y)) 1 2))`> = ['prim', true]
const maintest_isnumber_14: Cion.RawLisp<`(number? (:x {:x 1}))`> = ['prim', true]
const maintest_isnumber_15: Cion.RawLisp<`(number? (first [0 '1' 2]))`> = ['prim', true]
const maintest_isnumber_16: Cion.RawLisp<`(number? (let [x 1 y 2] (+ x y)))`> = ['prim', true]
const maintest_isnumber_17: Cion.RawLisp<`(number? (let [] (+ 1 2)))`> = ['prim', true]
const maintest_isnumber_18: Cion.RawLisp<`(number? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', true]
