import type Cion from '../src/index.ts'
 
const maintest_isodd_0: Cion.RawLisp<`(odd? 1)`> = ['prim', true]
const maintest_isodd_1: Cion.RawLisp<`(odd? -1)`> = ['prim', true]
const maintest_isodd_00: Cion.RawLisp<`(odd? 2)`> = ['prim', false]
const maintest_isodd_11: Cion.RawLisp<`(odd? -2)`> = ['prim', false]
const maintest_isodd_2: Cion.RawLisp<`(odd? 29438)`> = ['prim', false]
const maintest_isodd_21: Cion.RawLisp<`(odd? 29439)`> = ['prim', true]
const maintest_isodd_3: Cion.RawLisp<`(odd? '')`> = ['prim', false]
const maintest_isodd_4: Cion.RawLisp<`(odd? '102')`> = ['prim', false]
const maintest_isodd_5: Cion.RawLisp<`(odd? true)`> = ['prim', false]
const maintest_isodd_6: Cion.RawLisp<`(odd? [])`> = ['prim', false]
const maintest_isodd_7: Cion.RawLisp<`(odd? [1 2 3])`> = ['prim', false]
const maintest_isodd_8: Cion.RawLisp<`(odd? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isodd_9: Cion.RawLisp<`(odd? {:x 1 :y 1})`> = ['prim', false]
const maintest_isodd_10: Cion.RawLisp<`(odd? nil)`> = ['prim', false]
const maintest_isodd_110: Cion.RawLisp<`(odd? (+ 1 2))`> = ['prim', true]
const maintest_isodd_12: Cion.RawLisp<`(odd? ((fn [] (+ 1 2))))`> = ['prim', true]
const maintest_isodd_13: Cion.RawLisp<`(odd? ((fn [x y] (+ x y)) 1 2))`> = ['prim', true]
const maintest_isodd_14: Cion.RawLisp<`(odd? (:x {:x 1}))`> = ['prim', true]
const maintest_isodd_15: Cion.RawLisp<`(odd? (first [-1 '1' 2]))`> = ['prim', true]
const maintest_isodd_16: Cion.RawLisp<`(odd? (let [x 1 y 2] (+ x y)))`> = ['prim', true]
const maintest_isodd_17: Cion.RawLisp<`(odd? (let [] (+ 1 2)))`> = ['prim', true]
const maintest_isodd_18: Cion.RawLisp<`(odd? (+ 4 (let [x 1 y 2] (+ x y))))`> = ['prim', true]
