import type Cion from '../src/index.ts'

const maintest_isposint_0: Cion.RawLisp<`(pos-int? 1)`> = ['prim', true]
const maintest_isposint_1: Cion.RawLisp<`(pos-int? -1)`> = ['prim', false]
const maintest_isposint_2: Cion.RawLisp<`(pos-int? 29438)`> = ['prim', true]
const maintest_isposint_3: Cion.RawLisp<`(pos-int? '')`> = ['prim', false]
const maintest_isposint_4: Cion.RawLisp<`(pos-int? '102')`> = ['prim', false]
const maintest_isposint_5: Cion.RawLisp<`(pos-int? true)`> = ['prim', false]
const maintest_isposint_6: Cion.RawLisp<`(pos-int? [])`> = ['prim', false]
const maintest_isposint_7: Cion.RawLisp<`(pos-int? [1 2 3])`> = ['prim', false]
const maintest_isposint_8: Cion.RawLisp<`(pos-int? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isposint_9: Cion.RawLisp<`(pos-int? {:x 1 :y 1})`> = ['prim', false]
const maintest_isposint_10: Cion.RawLisp<`(pos-int? nil)`> = ['prim', false]
const maintest_isposint_11: Cion.RawLisp<`(pos-int? (+ 1 2))`> = ['prim', true]
const maintest_isposint_12: Cion.RawLisp<`(pos-int? ((fn [] (+ 1 2))))`> = ['prim', true]
const maintest_isposint_13: Cion.RawLisp<`(pos-int? ((fn [x y] (+ x y)) 1 2))`> = ['prim', true]
const maintest_isposint_14: Cion.RawLisp<`(pos-int? (:x {:x 1}))`> = ['prim', true]
const maintest_isposint_15: Cion.RawLisp<`(pos-int? (first [0 '1' 2]))`> = ['prim', true]
const maintest_isposint_16: Cion.RawLisp<`(pos-int? (let [x 1 y 2] (+ x y)))`> = ['prim', true]
const maintest_isposint_17: Cion.RawLisp<`(pos-int? (let [] (+ 1 2)))`> = ['prim', true]
const maintest_isposint_18: Cion.RawLisp<`(pos-int? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', true]
