import type Cion from '../src/index.ts'

const maintest_ispos_0: Cion.RawLisp<`(pos? 1)`> = ['prim', true]
const maintest_ispos_1: Cion.RawLisp<`(pos? -1)`> = ['prim', false]
const maintest_ispos_2: Cion.RawLisp<`(pos? 29438)`> = ['prim', true]
const maintest_ispos_3: Cion.RawLisp<`(pos? '')`> = ['prim', false]
const maintest_ispos_4: Cion.RawLisp<`(pos? '102')`> = ['prim', false]
const maintest_ispos_5: Cion.RawLisp<`(pos? true)`> = ['prim', false]
const maintest_ispos_6: Cion.RawLisp<`(pos? [])`> = ['prim', false]
const maintest_ispos_7: Cion.RawLisp<`(pos? [1 2 3])`> = ['prim', false]
const maintest_ispos_8: Cion.RawLisp<`(pos? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_ispos_9: Cion.RawLisp<`(pos? {:x 1 :y 1})`> = ['prim', false]
const maintest_ispos_10: Cion.RawLisp<`(pos? nil)`> = ['prim', false]
const maintest_ispos_11: Cion.RawLisp<`(pos? (- 1 2))`> = ['prim', false]
const maintest_ispos_12: Cion.RawLisp<`(pos? ((fn [] (- 1 2))))`> = ['prim', false]
const maintest_ispos_13: Cion.RawLisp<`(pos? ((fn [x y] (- x y)) 1 2))`> = ['prim', false]
const maintest_ispos_14: Cion.RawLisp<`(pos? (:x {:x -1}))`> = ['prim', false]
const maintest_ispos_15: Cion.RawLisp<`(pos? (first [-1 '1' 2]))`> = ['prim', false]
const maintest_ispos_16: Cion.RawLisp<`(pos? (let [x 1 y 2] (- x y)))`> = ['prim', false]
const maintest_ispos_17: Cion.RawLisp<`(pos? (let [] (- 1 2)))`> = ['prim', false]
const maintest_ispos_18: Cion.RawLisp<`(pos? (* 3 (let [x 1 y 2] (- x y))))`> = ['prim', false]

const maintest_ispos_diff_0: Cion.RawLisp<`(pos? 1/2)`>   = ['prim', true]
const maintest_ispos_diff_1: Cion.RawLisp<`(pos? -1/2)`>  = ['prim', false]
const maintest_ispos_diff_2: Cion.RawLisp<`(pos? -3/1)`>  = ['prim', false]
const maintest_ispos_diff_3: Cion.RawLisp<`(pos? 3/1)`>   = ['prim', true]
const maintest_ispos_diff_4: Cion.RawLisp<`(pos? -3/-1)`> = ['prim', true]
const maintest_ispos_diff_5: Cion.RawLisp<`(pos? 3/-1)`>  = ['prim', false]
