import type Cion from '../src/index.ts'

const maintest_isratio_0: Cion.RawLisp<`(ratio? 1)`> = ['prim', false]
const maintest_isratio_1: Cion.RawLisp<`(ratio? -1)`> = ['prim', false]
const maintest_isratio_2: Cion.RawLisp<`(ratio? 29438)`> = ['prim', false]
const maintest_isratio_3: Cion.RawLisp<`(ratio? '')`> = ['prim', false]
const maintest_isratio_4: Cion.RawLisp<`(ratio? '102')`> = ['prim', false]
const maintest_isratio_5: Cion.RawLisp<`(ratio? false)`> = ['prim', false]
const maintest_isratio_6: Cion.RawLisp<`(ratio? [])`> = ['prim', false]
const maintest_isratio_7: Cion.RawLisp<`(ratio? [1 2 3])`> = ['prim', false]
const maintest_isratio_8: Cion.RawLisp<`(ratio? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isratio_9: Cion.RawLisp<`(ratio? {:x 1 :y 1})`> = ['prim', false]
const maintest_isratio_10: Cion.RawLisp<`(ratio? nil)`> = ['prim', false]
const maintest_isratio_11: Cion.RawLisp<`(ratio? (+ 1 2))`> = ['prim', false]
const maintest_isratio_12: Cion.RawLisp<`(ratio? ((fn [] (+ 1 2))))`> = ['prim', false]
const maintest_isratio_13: Cion.RawLisp<`(ratio? ((fn [x y] (+ x y)) 1 2))`> = ['prim', false]
const maintest_isratio_13x: Cion.RawLisp<`(ratio? inc)`> = ['prim', false]
const maintest_isratio_14: Cion.RawLisp<`(ratio? (:x {:x 1}))`> = ['prim', false]
const maintest_isratio_15: Cion.RawLisp<`(ratio? (first [0 '1' 2]))`> = ['prim', false]
const maintest_isratio_16: Cion.RawLisp<`(ratio? (let [x 1 y 2] (+ x y)))`> = ['prim', false]
const maintest_isratio_17: Cion.RawLisp<`(ratio? (let [] (+ 1 2)))`> = ['prim', false]
const maintest_isratio_18: Cion.RawLisp<`(ratio? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', false]
const maintest_isratio_19: Cion.RawLisp<`(ratio? ((fn [] (str 'a' 'b'))))`> = ['prim', false]

const maratioest_isratio_diff_0: Cion.RawLisp<`(ratio? 1/2)`>   = ['prim', true]
const maratioest_isratio_diff_1: Cion.RawLisp<`(ratio? -1/2)`>  = ['prim', true]
const maratioest_isratio_diff_2: Cion.RawLisp<`(ratio? -3/1)`>  = ['prim', false]
const maratioest_isratio_diff_3: Cion.RawLisp<`(ratio? 3/1)`>   = ['prim', false]
const maratioest_isratio_diff_4: Cion.RawLisp<`(ratio? -3/-1)`> = ['prim', false]
const maratioest_isratio_diff_5: Cion.RawLisp<`(ratio? 3/-1)`>  = ['prim', false]
