import type Cion from '../src/index.ts'
 
const maintest_issome_0: Cion.RawLisp<`(some? 1)`> = ['prim', true]
const maintest_issome_1: Cion.RawLisp<`(some? -1)`> = ['prim', true]
const maintest_issome_2: Cion.RawLisp<`(some? 29438)`> = ['prim', true]
const maintest_issome_3: Cion.RawLisp<`(some? '')`> = ['prim', true]
const maintest_issome_4: Cion.RawLisp<`(some? '102')`> = ['prim', true]
const maintest_issome_5: Cion.RawLisp<`(some? true)`> = ['prim', true]
const maintest_issome_6: Cion.RawLisp<`(some? [])`> = ['prim', true]
const maintest_issome_7: Cion.RawLisp<`(some? [1 2 3])`> = ['prim', true]
const maintest_issome_8: Cion.RawLisp<`(some? (fn [x y] (+ x y)))`> = ['prim', true]
const maintest_issome_9: Cion.RawLisp<`(some? {:x 1 :y 1})`> = ['prim', true]
const maintest_issome_10: Cion.RawLisp<`(some? nil)`> = ['prim', false]
const maintest_issome_11: Cion.RawLisp<`(some? (+ 1 2))`> = ['prim', true]
const maintest_issome_12: Cion.RawLisp<`(some? ((fn [] (+ 1 2))))`> = ['prim', true]
const maintest_issome_13: Cion.RawLisp<`(some? ((fn [x y] (+ x y)) 1 2))`> = ['prim', true]
const maintest_issome_14: Cion.RawLisp<`(some? (:x {:x 1}))`> = ['prim', true]
const maintest_issome_15: Cion.RawLisp<`(some? (first [0 '1' 2]))`> = ['prim', true]
const maintest_issome_16: Cion.RawLisp<`(some? (let [x 1 y 2] (+ x y)))`> = ['prim', true]
const maintest_issome_17: Cion.RawLisp<`(some? (let [] (+ 1 2)))`> = ['prim', true]
const maintest_issome_18: Cion.RawLisp<`(some? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', true]
