import type Cion from '../src/index.ts'

const maintest_isvector_0: Cion.RawLisp<`(vector? 1)`> = ['prim', false]
const maintest_isvector_1: Cion.RawLisp<`(vector? -1)`> = ['prim', false]
const maintest_isvector_2: Cion.RawLisp<`(vector? 29438)`> = ['prim', false]
const maintest_isvector_3: Cion.RawLisp<`(vector? '')`> = ['prim', false]
const maintest_isvector_4: Cion.RawLisp<`(vector? '102')`> = ['prim', false]
const maintest_isvector_5: Cion.RawLisp<`(vector? false)`> = ['prim', false]
const maintest_isvector_6: Cion.RawLisp<`(vector? [])`> = ['prim', true]
const maintest_isvector_7: Cion.RawLisp<`(vector? [1 2 3])`> = ['prim', true]
const maintest_isvector_8: Cion.RawLisp<`(vector? (fn [x y] (+ x y)))`> = ['prim', false]
const maintest_isvector_9: Cion.RawLisp<`(vector? {:x 1 :y 1})`> = ['prim', false]
const maintest_isvector_10: Cion.RawLisp<`(vector? nil)`> = ['prim', false]
const maintest_isvector_11: Cion.RawLisp<`(vector? (+ 1 2))`> = ['prim', false]
const maintest_isvector_12: Cion.RawLisp<`(vector? ((fn [] (+ 1 2))))`> = ['prim', false]
const maintest_isvector_13: Cion.RawLisp<`(vector? ((fn [x y] (+ x y)) 1 2))`> = ['prim', false]
const maintest_isvector_14: Cion.RawLisp<`(vector? (:x {:x 1}))`> = ['prim', false]
const maintest_isvector_15: Cion.RawLisp<`(vector? (first [0 '1' 2]))`> = ['prim', false]
const maintest_isvector_16: Cion.RawLisp<`(vector? (let [x 1 y 2] (+ x y)))`> = ['prim', false]
const maintest_isvector_17: Cion.RawLisp<`(vector? (let [] (+ 1 2)))`> = ['prim', false]
const maintest_isvector_18: Cion.RawLisp<`(vector? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', false]
const maintest_isvector_19: Cion.RawLisp<`(vector? ((fn [] (str 'a' 'b'))))`> = ['prim', false]
const maintest_isvector_20: Cion.RawLisp<`(vector? ((fn [x y] (str x y)) 'a' 'b'))`> = ['prim', false]
const maintest_isvector_21: Cion.RawLisp<`(vector? (:x {:x '111'}))`> = ['prim', false]
const maintest_isvector_22: Cion.RawLisp<`(vector? (first ['0' '1' 2]))`> = ['prim', false]
const maintest_isvector_23: Cion.RawLisp<`(vector? (let [x 'a' y 'b'] (str x y)))`> = ['prim', false]
const maintest_isvector_24: Cion.RawLisp<`(vector? (let [] (str 'a' 'b')))`> = ['prim', false]
const maintest_isvector_25: Cion.RawLisp<`(vector? (str 'c' (let [x 'a' y 'b'] (str x y))))`> = ['prim', false]
const maintest_isvector_letfn_19: Cion.RawLisp<`(vector? ((fn [] [0 1])))`> = ['prim', true]
const maintest_isvector_letfn_20: Cion.RawLisp<`(vector? ((fn [x y] [x y]) 'a' 'b'))`> = ['prim', true]
const maintest_isvector_letfn_21: Cion.RawLisp<`(vector? (:x {:x ['111']}))`> = ['prim', true]
const maintest_isvector_letfn_22: Cion.RawLisp<`(vector? (first [['0'] '1' 2]))`> = ['prim', true]
const maintest_isvector_letfn_23: Cion.RawLisp<`(vector? (let [x 'a' y 'b'] [x y]))`> = ['prim', true]
const maintest_isvector_letfn_24: Cion.RawLisp<`(vector? (let [] ['a' 'b']))`> = ['prim', true]
const maintest_isvector_letfn_25: Cion.RawLisp<`(vector? ['c' (let [x 'a' y 'b'] [x y])])`> = ['prim', true]

