import type Cion from '../src/index'

const mod_test0 : Cion.Lisp<`(mod 10 5)`> = '0'
const mod_test1 : Cion.Lisp<`(mod 10 10)`> = '0'
const mod_test2 : Cion.Lisp<`(mod 1 1)`> = '0'
const mod_test3 : Cion.Lisp<`(mod 1 0)`> = 'nil'
const mod_test4 : Cion.Lisp<`(mod 0 1)`> = '0'
const mod_test5 : Cion.Lisp<`(mod 0 0)`> = 'nil'
const mod_test6 : Cion.Lisp<`(mod 5 10)`> = '5'
const mod_test7 : Cion.Lisp<`(mod 2 5)`> = '2'
const mod_test8 : Cion.Lisp<`(mod 17 5)`> = '2'
const mod_test9 : Cion.Lisp<`(mod 17 3)`> = '2'
const mod_test10 : Cion.Lisp<`(mod 17 6)`> = '5'
const mod_test11 : Cion.Lisp<`(mod 17 -6)`> = '-1'

const mod_test01_fc : Cion.Lisp<`(mod -10 3)`> = '2'
const mod_test2_fc : Cion.Lisp<`(mod 10 -3)`> = '-2'
const mod_test3_fc : Cion.Lisp<`(mod -10 -3)`> = '-1'
const mod_test4_fc : Cion.Lisp<`(mod 10 3)`> = '1'

// ---

const mod_test0a : Cion.Lisp<`(mod 10/3 5/3)`> = '0'
const mod_test1a : Cion.Lisp<`(mod 10/3 10/3)`> = '0'
const mod_test2a : Cion.Lisp<`(mod 1/3 1/3)`> = '0'
const mod_test3a : Cion.Lisp<`(mod 1/3 0)`> = 'nil'
const mod_test6a : Cion.Lisp<`(mod 0 1/3)`> = '0'
const mod_test4a : Cion.Lisp<`(mod 0 0)`> = 'nil'
const mod_test5a : Cion.Lisp<`(mod 5/3 10/3)`> = '5/3'

const mod_test0bpp : Cion.Lisp<`(mod 10/3 5/2)`>   = '5/6'
const mod_test0bpm : Cion.Lisp<`(mod 10/3 -5/2)`>  = '-5/3'
const mod_test0bmp : Cion.Lisp<`(mod -10/3 5/2)`>  = '5/3'
const mod_test0bmm : Cion.Lisp<`(mod -10/3 -5/2)`> = '-5/6'

const mod_test1bpp : Cion.Lisp<`(mod 11/3 10/7)`>   = '17/21'
const mod_test1bpm : Cion.Lisp<`(mod 11/3 -10/7)`>  = '-13/21'
const mod_test1cbmp : Cion.Lisp<`(mod -11/3 10/7)`>  = '13/21'
const mod_test1bmm : Cion.Lisp<`(mod -11/3 -10/7)`> = '-17/21'

const mod_test2bpp : Cion.Lisp<`(mod 1/3 1/2)`>   = '1/3'
const mod_test2bpm : Cion.Lisp<`(mod 1/3 -1/2)`>  = '-1/6'
const mod_test2bmp : Cion.Lisp<`(mod -1/3 1/2)`>  = '1/6'
const mod_test2bmm : Cion.Lisp<`(mod -1/3 -1/2)`> = '-1/3'
const mod_test3bpp : Cion.Lisp<`(mod 1/2 1/3)`>   = '1/6'
const mod_test3bpm : Cion.Lisp<`(mod 1/2 -1/3)`>  = '-1/6'
const mod_test3bmp : Cion.Lisp<`(mod -1/2 1/3)`>  = '1/6'
const mod_test3bmm : Cion.Lisp<`(mod -1/2 -1/3)`> = '-1/6'

const mod_test0c : Cion.Lisp<`(mod 10/3 7)`> = '10/3'
const mod_test1c : Cion.Lisp<`(mod 1/3 7)`> = '1/3'
const mod_test2c : Cion.Lisp<`(mod 7 10/3)`> = '1/3'

const mod_test_f0 : Cion.Lisp<`(mod 1 0)`> = 'nil'
const mod_test_f1 : Cion.Lisp<`(mod 1 nil)`>['ast']['error'] = 'LispRemOrModError2'
const mod_est_f2 : Cion.Lisp<`(mod 1 true)`>['ast']['error'] = 'LispRemOrModError2'
const mod_test_f3 : Cion.Lisp<`(mod 1 'string')`>['ast']['error'] = 'LispRemOrModError2'
const mod_test_f4 : Cion.Lisp<`(mod 1 mod)`>['ast']['error'] = 'LispRemOrModError2'
const mod_test_f5 : Cion.Lisp<`(mod 1 (fn [x] x))`>['ast']['error'] = 'LispRemOrModError2'
const mod_test_f6 : Cion.Lisp<`(mod 1 [])`>['ast']['error'] = 'LispRemOrModError2'
const mod_test_f7 : Cion.Lisp<`(mod 1 {})`>['ast']['error'] = 'LispRemOrModError2'

const mod_test_f8 : Cion.Lisp<`(mod 1 2/3)`> = '1/3'
const mod_test_f : Cion.Lisp<`(mod 1 -2/3)`> = '-1/3'
