import type Cion from '../src/index'

const rem_test0 : Cion.Lisp<`(rem 10 5)`> = '0'
const rem_test1 : Cion.Lisp<`(rem 10 10)`> = '0'
const rem_test2 : Cion.Lisp<`(rem 1 1)`> = '0'
const rem_test3 : Cion.Lisp<`(rem 1 0)`> = 'nil'
const rem_test4 : Cion.Lisp<`(rem 0 1)`> = '0'
const rem_test5 : Cion.Lisp<`(rem 0 0)`> = 'nil'
const rem_test6 : Cion.Lisp<`(rem 5 10)`> = '5'
const rem_test7 : Cion.Lisp<`(rem 2 5)`> = '2'
const rem_test8 : Cion.Lisp<`(rem 17 5)`> = '2'
const rem_test9 : Cion.Lisp<`(rem 17 3)`> = '2'
const rem_test10 : Cion.Lisp<`(rem 17 6)`> = '5'
const rem_test11 : Cion.Lisp<`(rem 17 -6)`> = '5'

const rem_test01_fc : Cion.Lisp<`(rem -10 3)`> = '-1'
const rem_test2_fc : Cion.Lisp<`(rem 10 -3)`> = '1'
const rem_test3_fc : Cion.Lisp<`(rem -10 -3)`> = '-1'
const rem_test4_fc : Cion.Lisp<`(rem 10 3)`> = '1'

// ---

const rem_test0a : Cion.Lisp<`(rem 10/3 5/3)`> = '0'
const rem_test1a : Cion.Lisp<`(rem 10/3 10/3)`> = '0'
const rem_test2a : Cion.Lisp<`(rem 1/3 1/3)`> = '0'
const rem_test3a : Cion.Lisp<`(rem 1/3 0)`> = 'nil'
const rem_test6a : Cion.Lisp<`(rem 0 1/3)`> = '0'
const rem_test4a : Cion.Lisp<`(rem 0 0)`> = 'nil'
const rem_test5a : Cion.Lisp<`(rem 5/3 10/3)`> = '5/3'

const rem_test0bpp : Cion.Lisp<`(rem 10/3 5/2)`>   = '5/6'
const rem_test0bpm : Cion.Lisp<`(rem 10/3 -5/2)`>  = '5/6'
const rem_test0bmp : Cion.Lisp<`(rem -10/3 5/2)`>  = '-5/6'
const rem_test0bmm : Cion.Lisp<`(rem -10/3 -5/2)`> = '-5/6'

const rem_test1bpp : Cion.Lisp<`(rem 11/3 10/7)`>   = '17/21'
const rem_test1bpm : Cion.Lisp<`(rem 11/3 -10/7)`>  = '17/21'
const rem_test1bmp : Cion.Lisp<`(rem -11/3 10/7)`>  = '-17/21'
const rem_test1bmm : Cion.Lisp<`(rem -11/3 -10/7)`> = '-17/21'

const rem_test2bpp : Cion.Lisp<`(rem 1/3 1/2)`>   = '1/3'
const rem_test2bpm : Cion.Lisp<`(rem 1/3 -1/2)`>  = '1/3'
const rem_test2bmp : Cion.Lisp<`(rem -1/3 1/2)`>  = '-1/3'
const rem_test2bmm : Cion.Lisp<`(rem -1/3 -1/2)`> = '-1/3'
const rem_test3bpp : Cion.Lisp<`(rem 1/2 1/3)`>   = '1/6'
const rem_test3bpm : Cion.Lisp<`(rem 1/2 -1/3)`>  = '1/6'
const rem_test3bmp : Cion.Lisp<`(rem -1/2 1/3)`>  = '-1/6'
const rem_test3bmm : Cion.Lisp<`(rem -1/2 -1/3)`> = '-1/6'

const rem_test0c : Cion.Lisp<`(rem 10/3 7)`> = '10/3'
const rem_test1c : Cion.Lisp<`(rem 1/3 7)`> = '1/3'
const rem_test2c : Cion.Lisp<`(rem 7 10/3)`> = '1/3'

const rem_test_f0 : Cion.Lisp<`(rem 1 0)`> = 'nil'
const rem_test_f1 : Cion.Lisp<`(rem 1 nil)`>['ast']['error'] = 'LispRemOrModError2'
const rem_est_f2 : Cion.Lisp<`(rem 1 true)`>['ast']['error'] = 'LispRemOrModError2'
const rem_test_f3 : Cion.Lisp<`(rem 1 'string')`>['ast']['error'] = 'LispRemOrModError2'
const rem_test_f4 : Cion.Lisp<`(rem 1 rem)`>['ast']['error'] = 'LispRemOrModError2'
const rem_test_f5 : Cion.Lisp<`(rem 1 (fn [x] x))`>['ast']['error'] = 'LispRemOrModError2'
const rem_test_f6 : Cion.Lisp<`(rem 1 [])`>['ast']['error'] = 'LispRemOrModError2'
const rem_test_f7 : Cion.Lisp<`(rem 1 {})`>['ast']['error'] = 'LispRemOrModError2'

const rem_test_f8 : Cion.Lisp<`(rem 1 2/3)`> = '1/3'
const rem_test_f : Cion.Lisp<`(rem 1 -2/3)`> = '1/3'
