// import type Cion from '../src/index.js'
 
// const maintest_issymbol_0: Cion.RawLisp<`(symbol? 1)`> = ['prim', false]
// const maintest_issymbol_1: Cion.RawLisp<`(symbol? -1)`> = ['prim', false]
// const maintest_issymbol_2: Cion.RawLisp<`(symbol? 29438)`> = ['prim', false]
// const maintest_issymbol_3: Cion.RawLisp<`(symbol? '')`> = ['prim', false]
// const maintest_issymbol_4: Cion.RawLisp<`(symbol? '102')`> = ['prim', false]
// const maintest_issymbol_5: Cion.RawLisp<`(symbol? false)`> = ['prim', false]
// const maintest_issymbol_6: Cion.RawLisp<`(symbol? [])`> = ['prim', false]
// const maintest_issymbol_7: Cion.RawLisp<`(symbol? [1 2 3])`> = ['prim', false]
// const maintest_issymbol_8: Cion.RawLisp<`(symbol? (fn [x y] (+ x y)))`> = ['prim', false]
// const maintest_issymbol_9: Cion.RawLisp<`(symbol? {:x 1 :y 1})`> = ['prim', false]
// const maintest_issymbol_10: Cion.RawLisp<`(symbol? nil)`> = ['prim', false]
// const maintest_issymbol_11: Cion.RawLisp<`(symbol? (+ 1 2))`> = ['prim', false]
// const maintest_issymbol_12: Cion.RawLisp<`(symbol? ((fn [] (+ 1 2))))`> = ['prim', false]
// const maintest_issymbol_13: Cion.RawLisp<`(symbol? ((fn [x y] (+ x y)) 1 2))`> = ['prim', false]
// const maintest_issymbol_14: Cion.RawLisp<`(symbol? (:x {:x 1}))`> = ['prim', false]
// const maintest_issymbol_15: Cion.RawLisp<`(symbol? (first [0 '1' 2]))`> = ['prim', false]
// const maintest_issymbol_16: Cion.RawLisp<`(symbol? (let [x 1 y 2] (+ x y)))`> = ['prim', false]
// const maintest_issymbol_17: Cion.RawLisp<`(symbol? (let [] (+ 1 2)))`> = ['prim', false]
// const maintest_issymbol_18: Cion.RawLisp<`(symbol? (+ 3 (let [x 1 y 2] (+ x y))))`> = ['prim', false]
