import type * as Bit from '../bit/index.js'
import type * as Decimal from '../decimal/index.js'
import type { StrUtil as str } from '../strutil.js'
import type { regexConst } from './const.js'
import type { Util as u } from '../util.js'
import type * as Vec from '../vector/index.js'

// ---------------
// -- Constants
// ---------------

export type CompTape = CompFrame | CompFrame[] | CompEnv
export type CompState = string
export type CompFrame = string | CompTape[] | CompFrame[] | FrameCharaClass
export type FrameCharaClass = ['chara-class', string[]]
export type CompEnv = {state: CompState, tapes: CompTape[], frames: CompFrame[]}
export type InitCompEnv = {state: '', tapes: [], frames: []}

export type CompSig = '?' | '*' | 'group' | 'or-group' | 'chara-class'

type InitStack = []
type InitLast = ''
type InitCondition = ''

// --------------------------------------------
// -- Compiler (Character Class Syntax (`[a-Z]`))
// --------------------------------------------

/**
Compiles a regex range `x-y` into a tuple containing all ASCII characters between `x` and `y` (inclusive).

```typescript
type Expected_lowers = CharaClass<"a-d"> //=> ["a", "b", "c", "d"]
type Expected_uppers = CharaClass<"A-D"> //=> ["A", "B", "C", "D"]
type Expected_nums = CharaClass<"1-4"> //=> ["1", "2", "3", "4"]
```
*/
export type CharaClass<
  S extends string> =
  S extends `${infer f extends keyof regexConst.TransNumber}-${infer s extends keyof regexConst.TransNumber}${infer _rest}`
    ? Vec.InterByBit<regexConst.ASCII, regexConst.TransNumber[f], regexConst.TransNumber[s]>
  : never

/**
Computes the complement of a character set.

Used for negative character classes `[^...]` by excluding specified characters from the ASCII set.

```typescript
type Expected_lowers = NegCharaClass<[...regexConst.WordList, ...regexConst.NumList]> //=> [ '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~', ' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@']
```
*/
type NegCharaClass<
  V extends (keyof regexConst.TransNumber)[]> =
  u.DissocKeys<regexConst.TransNumber, V> extends infer KU extends Record<PropertyKey, unknown>
    ? u.KeysTuple<KU> extends infer R
      ? R
    : never
  : never

/**
Returns a chara class tuple.
*/
type GenCharaClassTuple<
  Sig extends '[' | '[^'
, R extends (keyof regexConst.TransNumber)[]> =
  Sig extends '['
    ? R
  : NegCharaClass<R>

type CompOption = {negExpand: boolean}
type InitCompOption = {negExpand: true}

/**
Compiles a regex character class string into an AST.

Returns a two-members tuple.
1. A two-member tuple - the 'chara-class' signature and the chara class AST.
2. A rest regex generated by consuming the chara-class in the passed regex.

```typescript
type Expected_rest = CompCharaClass<'[abd\\d]rest', '['> //=> [['chara-class', ['a', 'b', 'd', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']], 'rest']
```
*/
export type CompCharaClass<
  S extends string
, Sig extends '[' | '[^'
, Option extends CompOption = InitCompOption> =
_CompCharaClass<S, Sig, Option>

type _CompCharaClass<
  S extends string
, Sig extends '[' | '[^'
, Option extends CompOption = InitCompOption
, R extends (keyof regexConst.TransNumber)[] = []
, IsReading extends boolean = false> =
  S extends ''
    ? [['chara-class', true extends (Option['negExpand']) ? GenCharaClassTuple<Sig, R> : R], '']
  : str.RegCut<S> extends [infer regFirst extends string
                          , infer regRest extends string]
    ? regFirst extends ']'
      ? [['chara-class', true extends (Option['negExpand']) ? GenCharaClassTuple<Sig, R> : R], regRest]
    : regFirst extends '[' | '[^'
      ? IsReading extends false
        ? _CompCharaClass<regRest, Sig, Option, R, true>
      : _CompCharaClass<regRest, Sig, Option, [...R, ...(regFirst extends '[' ? ['['] : ['[', '^'])], true>
    : regFirst extends `\\${infer Escaped}`
      ? regFirst extends keyof regexConst.MetaChars
        ? _CompCharaClass<regRest, Sig, Option, [...R, ...regexConst.MetaChars[regFirst]], IsReading>
      : Escaped extends keyof regexConst.TransNumber
        ? _CompCharaClass<regRest, Sig, Option, [...R, Escaped], IsReading>
      : 'never6'
    : regFirst extends keyof regexConst.MetaChars
      ? _CompCharaClass<regRest, Sig, Option, [...R, ...regexConst.MetaChars[regFirst]], IsReading>
    : regFirst extends keyof regexConst.TransNumber
      ? _CompCharaClass<regRest, Sig, Option, [...R, regFirst], IsReading>
    : regFirst extends `${infer _fst}-${infer _trd}${infer _rest}`
      ? CharaClass<regFirst> extends infer Range extends (keyof regexConst.TransNumber)[]
        ? _CompCharaClass<regRest, Sig, Option, [...R, ...Range], IsReading>
      : never
    : never
  : never

// --------------------------------------------
// -- Compiler (Repeat Time Syntax (`{n,m}`))
// --------------------------------------------

/**
`limit` would be
  - a number greater than `min`
  - '='
  - '<'

- number : compile `{min,limit}`
- = : compile `{min}`
- < : compile `{min,}`
*/
export type ExpandMinMax<
  P extends CompFrame
, min extends string
, limit extends string> =
  limit extends '='
    ? Vec.RepeatByBit<min, P> extends infer Return // [todo] write extends directly
      ? Return extends CompFrame
        ? Return
      : never
    : never
  : limit extends '<'
    ? Vec.RepeatByBit<min, P> extends infer Drp extends unknown[]
      ? [...Drp, ['*', P]] extends infer Return // [todo] write extends directly
        ? Return extends CompFrame
          ? Return
        : never
      : never
    : never
  : Vec.RepeatByBit<min, P> extends infer _Dfst extends unknown[]
    ? Bit.BitSub<limit, min> extends infer _Dsub extends string
      ? Vec.RepeatByBit<_Dsub, ['?', P]> extends infer _Dsnd extends unknown[]
        ? [..._Dfst, ..._Dsnd] extends infer Return
          ? Return extends CompFrame
            ? Return
          : never
        : never
      : never
    : never
  : never

/**
Compile `{n,m}` syntax to 3-members tuple:
  - 1st + 2nd : `ExpandMinMax` arguments.
  - 3rd : Rest regex-string.

```typescript
type Bit_1 = "0000000000000001"
type Bit_15 = "0000000000001111"
type Bit_16 = "0000000000010000"

CompMinMax<'{1,15}rest'>  //=> [Bit_1, Bit_15, 'rest']
CompMinMax<'{15,16}rest'> //=> [Bit_15, Bit_16, 'rest']
CompMinMax<'{15,}rest'>   //=> [Bit_15, '<', 'rest']
CompMinMax<'{15}rest'>    //=> [Bit_15, '=', 'rest']
```

Used in a branch `regFirst extends '{'` of `recComp` defined in `regex-compiler.ts`
*/
export type CompMinMax<
  S extends string> =
  S extends `${infer s0}${infer s1}${infer s2}${infer Next}`
    ? [s0, s2] extends ['{', '}']
      ? [Decimal.DecimalToBit<s1>, '=', Next]
    : [s0, s2] extends ['{', ',']
      ? Next extends `${infer s3}${infer nNext}`
        ? s3 extends '}'
          ? [Decimal.DecimalToBit<s1>, '<', nNext]
        : nNext extends `${infer s4}${infer nnNext}`
          ? s4 extends '}'
            ? [Decimal.DecimalToBit<s1>, Decimal.DecimalToBit<s3>, nnNext]
          : nnNext extends `${infer s5}${infer FinNext}`
            ? s5 extends '}'
              ? [Decimal.DecimalToBit<s1>, Decimal.DecimalToBit<`${s3}${s4}`>, FinNext]
            : []
          : []
        : []
      : []
    : Next extends `${infer s3}${infer nNext}`
      ? s3 extends '}'
        ? [Decimal.DecimalToBit<`${s1}${s2}`>, '=', nNext]
      : s3 extends ','
        ? nNext extends `${infer s4}${infer nnNext}`
          ? s4 extends '}'
            ? [Decimal.DecimalToBit<`${s1}${s2}`>, '<', nnNext]
          : nnNext extends `${infer s5}${infer s6}${infer finNext}`
            ? s6 extends '}'
              ? [Decimal.DecimalToBit<`${s1}${s2}`>, Decimal.DecimalToBit<`${s4}${s5}`>, finNext]
            : []
          : []
        : []
      : []
    : []
  : []

// ---------------------
// -- Frame
// ---------------------

// Just merge frames to tapes at the tail.
type FrameToTape<
  F extends CompEnv> =
  F extends { state: infer State extends CompState
            , tapes: infer Tapes extends CompTape[]
            , frames: infer Frames extends CompFrame[]}
    ? { state: State
      , tapes: [...Tapes, ...Frames]
      , frames: [] }
  : never

// Just merge new token to frames.
type CompFraming<
  F extends CompEnv
, Fr extends CompFrame> =
  F extends {state: infer State extends CompState, tapes: infer Tapes extends CompTape[], frames: infer Frames extends CompFrame[]}
    ? { state: State
      , tapes: Tapes
      , frames: [...Frames, Fr] }
  : never

// ---------------------------
// -- Core Compiler
// ---------------------------

// -----------------------------------------------------
// [Note]
//
// `Last` delays the transfer of `env['frames']` to `env['tapes']`
// because evaluating `?`, `*`, and `+` requires the previous frame
// to wrap it.
//
// Therefore, all frames are transferred to tapes via `Last`.
// A portion of the regex is compiled into `Last`, and the previous `Last`
// is also packed into `frames` at the same time.
//
// `frames` are packed into `tapes` when the `state` switches.
// It happens if `Comp` reads a start of group or a similar construct.
// -----------------------------------------------------
// 
// Compiler
//
// This function compiles a regex string into an array, which we call a `tape`.
// The final result is a record containing both conditions and the tape.
//
// Here is how each element of the tape is translated from each part of the regex:
//
// - A single character like `c` is compiled into ['c'], a one-element array.
// - A group like `(abc)` is compiled into ['abc'].
// - A union group like `(a|b)` is compiled into ['a', 'b'].
//   These are passed into a `OrMatch`, where each element is read during matching.
// - A character set like `[ab]` is treated the same as a union group: ['a', 'b'].
//
// When `*` or `+` appears, the preceding element is packed into a tuple:
//   - The first item is the compiled array (e.g., ['abc', 'de'])
//   - The second item is the operator string: `*`.
//
//   For example, `(abc|de)*` first becomes ['abc', 'de'], then `*` is read,
//   so it becomes [['abc', 'de'], '*'] (example A).
//
//   If it's a `+`, another ['abc', 'de'] is appended to the tape, before the tuple A is added to it.
//   So the tape ends with: [...tape, ['abc', 'de'], ['abc', 'de'], '*'].
//
// `{n,m}` is compiled in the same way as `+`.
// - `(pat){2}` is expanded to `[['pat'], ['pat']]`
// - `(pat){2,}` is expanded to `[['pat'], ['pat'], [['pat'], '*']]`
// - `(pat){2,4}` is expanded to `[['pat'], ['pat'], [['pat'], '?'], [['pat'], '?']]`
//
// `^` and `$` are compiled into condition flags.
//
// ------------------------------------------------------
export type recComp<
  S extends string
, Option extends CompOption = InitCompOption
, Stack extends CompEnv[] = InitStack
, env extends CompEnv = InitCompEnv
, Last extends CompFrame = InitLast
, condition extends string = InitCondition> =
  S extends ''
    ? Last extends ''
      ? { r: { condition: condition
             , tapes: [...env['tapes'], ...env['frames']] } } extends infer r
        ? r
      : never
    : { r: { condition: condition
           , tapes: [...env['tapes'], ...[...env['frames'], Last]] } } extends infer r
      ? r
    : never
  : env extends { state:  infer State extends CompState
                , tapes:  infer Tapes extends CompTape[]
		, frames: infer Frames extends CompFrame[]}
    ? str.RegCut<S> extends [ infer regFirst extends string
                            , infer regRest extends string]
      ? regFirst extends '^' | '$'
        ? { r: recComp<regRest, Option, Stack, env, Last, `${condition}${regFirst}`> }
      : regFirst extends '[' | '[^'
        ? CompCharaClass<S, regFirst, Option> extends [infer classComped extends FrameCharaClass, infer classRest extends string]
          ? FrameToTape<CompFraming<env, Last>> extends infer FramedEnv extends CompEnv
            ? {r: recComp<classRest, Option, Stack, Last extends '' ? env : FramedEnv, classComped, condition>} extends infer a
              ? a
            : never
          : never
        : never
      : regFirst extends '('
        ? { r: recComp<regRest, Option, [Last extends InitLast ? env : CompFraming<env, Last>, ...Stack], {state: 'group', tapes: [], frames: []}, InitLast, condition> }
      : regFirst extends ')'
        ? Stack extends [ infer stackFirst extends CompEnv
                        , ...infer stackRest extends CompEnv[]]
          ? { r: recComp<regRest, Option, stackRest, stackFirst, [State, ...Tapes, ...(Last extends InitLast ? Frames : [[...Frames, Last]])], condition> }
        : never
      : regFirst extends '|'
        ? { r: recComp<regRest, Option, Stack, {state: 'or-group', tapes: [...Tapes, Last extends InitLast ? Frames : [...Frames, Last]], frames: []}, '', condition> }
      : regFirst extends '?' | '*'
        ? { r: recComp<regRest, Option, Stack, CompFraming<FrameToTape<env>, [regFirst, Last]>, InitLast, condition> }
      : regFirst extends '+'
        ? { r: recComp<regRest, Option, Stack, {state: State, tapes:[ ...Tapes, ...Frames, Last, ['*', Last]], frames: []}, InitLast, condition> }
      : regFirst extends '{'
        ? CompMinMax<S> extends [infer Min extends string,
                                 infer Max extends string
                                , infer Next extends string]
          ? ExpandMinMax<Last, Min, Max> extends infer Delayed extends CompFrame
            ? { r: recComp<Next, Option, Stack, env, Delayed, condition> extends infer r?r:never }
          : never
        : never
      : { r: recComp<regRest, Option, Stack, Last extends "" ? env : CompFraming<env, Last>, regFirst, condition> }
    : never
  : never

export type Comp<
  S extends string
, Option extends CompOption = InitCompOption> =
u.Rec<recComp<S, u.AssocWith<InitCompOption, Option>>>

export type * as regexCompiler from './regex-compiler.js'
